name: coverage

on:
  push:
    branches: [main]
    paths:
      - "calc/**"
      - ".github/workflows/codecov.yml"
  pull_request:
    branches: [main]
    paths:
      - "calc/**"
      - ".github/workflows/codecov.yml"
jobs:
  
  calling_work1:
    uses: rahulk789/codecov/.github/workflows/work1.yml@main
  calling_work2:
    uses: rahulk789/codecov/.github/workflows/work2.yml@main
  
  codecoverage:
    name: Measure code coverage
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - run: git branch
    - run: env  
    
    - name: Download artifact_1
      id: download-artifact1
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: true
      with:
        workflow: "work1.yml"
        name: "coverage-ubuntu-20.04-docker" 
            #,"coverage-ubuntu-20.04-crio","cov-ubuntu-20.04-crio",
   
    - name: Download artifacts_2
      id: download-artifact2
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: true
      with:
        workflow: "work2.yml"
        name: "cov-ubuntu-20.04-docker" 
    
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v3 
      with:
        files: ./calc/gover.coverprofile
